export const animeList = [
  {
    name: "Baki hanma season 2",
    pic: "https://images.justwatch.com/poster/306783512/s718/season-2.jpg",
    info: "To gain the skills he needs to surpass his powerful father, Baki enters Arizona State Prison to take on the notorious inmate known as Mr. Unchained.",
    link: "https://aniwave.to/watch/hanma-baki-season-2.oj4mz/ep-1",
  },
  {
    name: "Dragon ball super",
    pic: "https://m.media-amazon.com/images/M/MV5BY2I2MzI1ODYtMWRlOS00MzdhLWEyOWEtYWJhNmFiZTIxMGJhXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_.jpg",
    info: "Six months after the defeat of Majin Buu, The mighty Saiyan Son Goku continues his quest on becoming stronger.",
    link: "https://aniwave.to/watch/dragon-ball-super.7jly/ep-1",
  },
  {
    name: "Naruto: shippuden",
    pic: "https://m.media-amazon.com/images/M/MV5BZGFiMWFhNDAtMzUyZS00NmQ2LTljNDYtMmZjNTc5MDUxMzViXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    info: "Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninja in the village.",
    link: "https://aniwave.to/watch/naruto-shippuden.qv3/ep-1",
  },
  {
    name: "Tokyo revengers",
    pic: "https://upload.wikimedia.org/wikipedia/en/a/a8/TokyoRevengersSeason1.jpg",
    info: "Hanagaki Takemichi lives an unsatisfying life right up until his death. Waking up 12 years in the past, he reckons with the eventual fate of his friends and tries to prevent an unfortunate future.",
    link: "https://aniwave.to/watch/tokyo-revengers.vpq4/ep-0",
  },
  {
    name: "One Piece",
    pic: "https://upload.wikimedia.org/wikipedia/en/9/90/One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg",
    info: "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger. The famous mystery treasure named One Piece",
    link: "https://aniwave.to/watch/one-piece.ov8/ep-1",
  },
  {
    name: "JUJUTSU KAISEN Season 2",
    pic: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/77fb4ad8d5c781685695bc574eb34b0a.jpe",
    info: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    link: "https://aniwave.to/watch/jujutsu-kaisen-2nd-season.ll3x3/ep-1",
  },
  {
    name: "Bleach",
    pic: "https://upload.wikimedia.org/wikipedia/en/7/72/Bleachanime.png",
    info: "High school student Ichigo Kurosaki, who has the ability to see ghosts, gains soul reaper powers from Rukia Kuchiki and sets out to save the world from Hollows",
    link: "https://aniwave.to/watch/bleach.6j9/ep-1",
  },
  {
    name: "Ayakashi Triangle",
    pic: "https://m.media-amazon.com/images/M/MV5BOWRjNDgzNjAtOGJhNy00NjdkLWI1ZjctOTg0MDdhN2FkNjllXkEyXkFqcGdeQXVyOTE4NzcwNzI@._V1_FMjpg_UX1000_.jpg",
    info: "Matsuri Kazamaki and Suzu Kanade are childhood friends, bonded by their shared ability to see ayakashi - youkai in search of a life force to devour. However, in high school, their relationship deteriorates. As Suzu's one-sided feelings are growing, so is the difference in their ayakashi views: Matsuri considers all ayakashi a threat to his friend, while Suzu is an ayakashi medium: Someone who exudes a significant amount of life force compared to the average human and loves them all despite the risk.",
    link: "https://aniwave.to/watch/ayakashi-triangle.llrqm/ep-1",
  },
  {
    name: "Demon Slayer: Kimetsu no Yaiba Swordsmith",
    pic: "https://upload.wikimedia.org/wikipedia/en/8/80/Demon-Slayer-2023.jpeg",
    info: "All the Upper Rank Demons assemble at the Infinity Castle after Upper Six Demons' defeat.",
    link: "https://aniwave.to/watch/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc.3r7p6/ep-1",
  },
  {
    name: "Hunter x Hunter (2011)",
    pic: "https://m.media-amazon.com/images/M/MV5BNGM0YTk3MWEtN2JlZC00ZmZmLWIwMDktZTMxZGE5Zjc2MGExXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
    info: "Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks out his father, who left him when he was younger.",
    link: "https://aniwave.to/watch/hunter-x-hunter-2011.295/ep-1",
  },
  {
    name: "Classroom for Heroes",
    pic: "https://upload.wikimedia.org/wikipedia/en/9/9e/Eiy%C5%AB_Ky%C5%8Dshitsu_light_novel_volume_1_cover.jpg",
    info: "A long time ago, there existed a Demon Lord who terrorized throughout the world until a Hero stepped up to the stage and challenged the Demon Lord, ultimately defeating him and ending his reign. The Hero then created Rosewood Academy, an academy made to help heroes-in-training achieve supremacy and help defend the world when needed that enrolls only the best of the best. ",
    link: "https://aniwave.to/watch/eiyuu-kyoushitsu.w19r6/ep-1",
  },
  {
    name: "The Great Cleric",
    pic: "https://m.media-amazon.com/images/M/MV5BZWU4Y2Y2NDQtYWJmMi00NzIxLWE5MmEtYjA0NTE4Mjc1MTIxXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    info: "Earth's God of Destiny lost to Galdardia's Chief God for a bet and chose ten souls to hand over. Galdardia's Chief God handed those ten souls new vessels. Among those souls was Luciel, a salaryman, who fought against his destiny of death.",
    link: "https://aniwave.to/watch/seija-musou-salaryman-isekai-de-ikinokoru-tame-ni-ayumu-michi.ojloj/ep-1",
  },
  {
    name: "Black Clover",
    pic: "https://m.media-amazon.com/images/M/MV5BN2FlYjYxMTMtZGQzYy00OWU2LTkyYWMtNWJhODhmZmM0N2FhXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
    info: "Asta and Yuno were abandoned together at the same church and have been inseparable since. As children, they promised that they would compete against each other to see who would become the next Emperor Magus.",
    link: "https://aniwave.to/watch/black-clover.v2k6/ep-1",
  },
  {
    name: "Naruto",
    pic: "https://m.media-amazon.com/images/M/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
    info: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    link: "https://aniwave.to/watch/naruto.xx8z/ep-1",
  },
  {
    name: "Attack on titans",
    pic: "https://flxt.tmsimg.com/assets/p15767582_b_v9_ab.jpg",
    info: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    link: "https://aniwave.to/watch/attack-on-titan.kww/ep-1",
  },
  {
    name: "Dragon Ball Z",
    pic: "https://m.media-amazon.com/images/M/MV5BNGM5MTEyZDItZWNhOS00NzNkLTgwZTAtNWIzY2IzZmExOWMxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    info: "With the help of the powerful Dragonballs, a team of fighters led by the saiyan warrior Goku defend the planet earth from extraterrestrial enemies.",
    link: "https://aniwave.to/watch/dragon-ball-z.51ov/ep-1",
  },
  {
    name: "Boruto: Naruto Next Generations",
    pic: "https://m.media-amazon.com/images/M/MV5BYjM0MDRkYzctMTNhMS00ODYwLTgwMWItZDYxNDlhOGY1YjRlXkEyXkFqcGdeQXVyMzExMzk5MTQ@._V1_.jpg",
    info: "Son of Naruto Uzumaki, Boruto, follows his father's footsteps along with his friends to become great ninja. Throughout all their adventures, Boruto is determined to make his mark in the ninja world and live outside of his father's shadow.",
    link: "https://aniwave.to/watch/boruto-naruto-next-generations.97vm/ep-1",
  },
  {
    name: "Sweet Reincarnation",
    pic: "https://m.media-amazon.com/images/M/MV5BYzVmOThmZDktOTI1Ni00YTdhLWEzYzItZTUxYzdiMDZjNzMyXkEyXkFqcGdeQXVyMTU5NDMzOTg2._V1_FMjpg_UX1000_.jpg",
    info: "Nine-year-old Pastry Mille Morteln is from reincarnation and encounters the magical world. He must learn how to fight, utilizing his confectionary knowledge about pastry and discovering magic along the way.",
    link: "https://aniwave.to/watch/okashi-na-tensei.vv9xl/ep-1",
  },
];

export const newAnime = [
  {
    name: "Tokyo Revengers: Tenjiku-hen",
    pic: "https://m.media-amazon.com/images/M/MV5BYzk4NDc5MTAtZGQzOC00Y2MyLThkMGEtOGRkMzliOGNlYjkwXkEyXkFqcGdeQXVyMTA5NzUzODM4._V1_.jpg",
    info: "Hanagaki Takemichi lives an unsatisfying life right up until his death. Waking up 12 years in the past, he reckons with the eventual fate of his friends and tries to prevent an unfortunate future.",
    link: "https://aniwave.to/watch/tokyo-revengers-tenjiku-hen.2ow05/ep-1-preview",
  },
  {
    name: "Solo Leveling",
    pic: "https://m.media-amazon.com/images/M/MV5BMDM3M2YwZjgtM2JjYi00MGY1LWE4MjMtOWZkOGNkNDA0ZDAwXkEyXkFqcGdeQXVyMTEwNDU1MzEy._V1_.jpg",
    info: "Anime adaptation of the South Korean web novel 'Solo Leveling'",
    link: "https://aniwave.to/watch/solo-leveling.3rpv2/ep-preview",
  },
  {
    name: "Tsukimichi -Moonlit Fantasy- Season 2",
    pic: "https://cdn.myanimelist.net/images/anime/1996/137082.jpg",
    info: "The series tells the story of normal kid Makoto Misumi who, after being transported to a fantasy world to serve as its hero, is cut loose when the world's unnamed goddess decides he doesn't measure up to her standards of beauty.",
    link: "https://aniwave.to/watch/tsuki-ga-michibiku-isekai-douchuu-2.xrpw8/ep-preview",
  },
  {
    name: "The Legend of Magic Outfit",
    pic: "https://i0.wp.com/luciferdonghua.in/wp-content/uploads/2023/08/the-legend-of-magic-outfit-Lucifer-Donghua-1.webp",
    info: "A Mortal's Journey to Immortality",
    link: "https://aniwave.to/watch/mo-zhuang-chuanshuo.qx755/ep-1",
  },
  {
    name: "The Apothecary Diaries",
    pic: "https://m.media-amazon.com/images/M/MV5BN2JmNTE5ZDItMWQ3MC00ZGM3LWFmNTYtMzYzOGExNGYxMjU4XkEyXkFqcGdeQXVyODMyNTM0MjM@._V1_.jpg",
    info: "It follows Maomao as she is kidnapped and sold into service in the palace. She has a quick wit, a sharp mind, and knowledge of medicine, and she encounters a someone at least as perceptive as she is: the head eunuch, Jinshi.",
    link: "https://aniwave.to/watch/kusuriya-no-hitorigoto.9ojkn/ep-preview",
  },
  {
    name: "Frieren: Beyond Journey’s End",
    pic: "https://m.media-amazon.com/images/I/81hUX5XSZ1L._AC_UF1000,1000_QL80_.jpg",
    info: "An elf and her friends defeat a demon king in a great war. But the war is over, and the elf must search for a new way of life.",
    link: "https://aniwave.to/watch/sousou-no-frieren.3rp2y/ep-1-preview",
  },
  {
    name: "Rakshasa Street 3",
    pic: "https://img.animeschedule.net/production/assets/public/img/anime/jpg/default/zhen-hun-jie-3-9248b324b3.jpg",
    info: "Based on the Chinese Manhua. Requiem Street, where evil spirits are attracted to in order to destroy them. A place where spirits and humans co-exist, not all humans can enter Requiem Street.",
    link: "https://aniwave.to/watch/zhen-hun-jie-3.9ojz0/ep-1",
  },
  {
    name: "Fights Break Sphere 6",
    pic: "https://m.media-amazon.com/images/I/81keAOBFluL._AC_UF1000,1000_QL80_.jpg",
    info: "In order to take the magic fire from Medusa,Xiao Yan is accompanied by Yao Lao to go to the Tagore desert where the snake people live.However thirst let him mistakenly rush into the oasis which trigger a series of adventures...",
    link: "https://aniwave.to/watch/dou-po-cangqiong-nian-fan-2.n3w1l/ep-1",
  },
  {
    name: "The Seven Deadly Sins: Grudge of Edinburgh part 2",
    pic: "https://m.media-amazon.com/images/M/MV5BNzVkYTkwZGUtN2M5Zi00NWVmLTgzOWMtMmZmOGE3MGI4ZDc3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg",
    info: "Reunited with Lancelot for the first time since their tragic accident, Tristan must learn to conquer his inner demons in order to save his mother's life.",
    link: "https://aniwave.to/watch/nanatsu-no-taizai-ensa-no-edinburgh-part-2.llxm6/ep-1",
  },
  {
    name: "Odekake Kozame",
    pic: "https://cdn.myanimelist.net/images/anime/1464/136707.jpg",
    info: "The adventures of a baby shark in nostalgia-filled Yauo Town. Whether it's cider on a summer day, freeze pops, radio calisthenics, festival stalls, or hanging out with friends, the world sparkles when reflected in the eyes of the baby shark.",
    link: "https://aniwave.to/watch/odekake-kozame2.zlwvm/ep-1",
  },
  {
    name: "The Galaxy Emperor",
    pic: "https://luciferdonghua.in/wp-content/uploads/2023/07/the-galaxy-emperor.webp",
    info: "The Emperor of the Galaxy was placed in suspended animation shortly before his death, meaning that he has now lived for millions of years and all his potential heirs are long dead. This has caused all power in the galaxy to move down a rung.",
    link: "https://aniwave.to/watch/gaishi-dizun.020z9/ep-1",
  },
  {
    name: "4 Cut Hero",
    pic: "https://m.media-amazon.com/images/M/MV5BODk1MTUxMjQtMzVkMi00NTM2LWIzYjAtOWVmOGFkOWMzYWM2XkEyXkFqcGdeQXVyNjMxMTE5NTY@._V1_.jpg",
    info: "After defeating the Demon King, our Hero saves the princess and rides off into the horizon to start a new life - In his dreams - Little did he know that unemployment and mediocrity awaited him.",
    link: "https://aniwave.to/watch/si-ge-yongzhe.yqj5z/ep-1",
  },
  {
    name: "Pokémon WCS2023",
    pic: "https://worlds.pokemon.com/images/home/banner-bg1-mobile.webp",
    info: "An original animated series that tells the inspiring story of one girl's rise through competitive Pokémon Trading Card Game play. ",
    link: "https://aniwave.to/watch/pokemon-wcs2023.ll1jq/ep-1",
  },
  {
    name: "The Westward 5th Season",
    pic: "https://img.flawlessfiles.com/_r/300x400/100/4e/af/4eafe16d3b9ec7b2e47786ada0e50a0a/4eafe16d3b9ec7b2e47786ada0e50a0a.jpg",
    info: "The journey to the West was a conspiracy of heaven. After Sutra went missing for more than a decade, Heaven sent its army to search, in order not to let the Sutra once again fall into the hands of heaven, the journey to West begin again.",
    link: "https://aniwave.to/watch/xi-xing-ji-nian-bo-ju-ji.jvpy8/ep-1",
  },
];

export const updateAnime = [
  {
    name: "Jewelpet",
    pic: "https://m.media-amazon.com/images/M/MV5BYjEzZmVjYzctZTExNi00MjhmLWE5NzEtMzBkYjc4ZTkyZDU1XkEyXkFqcGdeQXVyNTk5OTgzMTY@._V1_FMjpg_UX1000_.jpg",
    info: "Ruby, a mischievous Japanese Hare from Jewel Land, is sent to Earth to retrieve all her friends.",
    link: "https://aniwave.to/watch/jewelpet.1ljw/ep-29",
  },
  {
    name: "Helck",
    pic: "https://m.media-amazon.com/images/M/MV5BNzZiMjE3OTQtMmFiNi00NjNmLWFkMGMtMzQzZmMxZDkyNWE3XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    info: "A human enters a tournament of demons to become the king of demons.",
    link: "https://aniwave.to/watch/helck.kwkxw/ep-8",
  },
  {
    name: "The Girl I Like Forgot Her Glasses",
    pic: "https://m.media-amazon.com/images/M/MV5BMjkwZWUxNzctYjBlOC00OWFiLWIwNjAtODgxMWYzMTIzNzM4XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_FMjpg_UX1000_.jpg",
    info: "A schoolboy develops a crush on his short-sighted schoolgirl classmate. Will he get close enough for her to see his feelings?",
    link: "https://aniwave.to/watch/suki-na-ko-ga-megane-wo-wasureta.02mkr/ep-9",
  },
  {
    name: "Odekake Kozame",
    pic: "https://cdn.myanimelist.net/images/anime/1464/136707.jpg",
    info: "The adventures of a baby shark in nostalgia-filled Yauo Town. Whether it's cider on a summer day, freeze pops, radio calisthenics, festival stalls, or hanging out with friends, the world sparkles when reflected in the eyes of the baby shark.",
    link: "https://aniwave.to/watch/odekake-kozame2.zlwvm/ep-1",
  },
  {
    name: "Yu☆Gi☆Oh! Go Rush!!",
    pic: "https://upload.wikimedia.org/wikipedia/en/f/f1/Yu-Gi-Oh%21_GO_RUSH%21%21_BR_Cover_1.jpg",
    info: "The Odo (Ohdo) twins, Yuhi and Yuamu, are elementary school students in charge of a company called Uchujin Toraburu Sodansha (UTS) that solves Earthling problems with aliens. During one of their jobs, they meet an alien called Yudiasu (Yudias), who came to Earth to learn about Rush Duels for his own reasons.",
    link: "https://aniwave.to/watch/yugioh-go-rush.80npy/ep-73",
  },
  {
    name: "Beyblade Burst Evolution",
    pic: "https://upload.wikimedia.org/wikipedia/en/7/76/BurstEvoKV.jpg",
    info: "Valt Aoi is a hot-blooded kid who loves to attack and wields a Beyblade named Valkyrie. His close friend Shu Kurenai is an elite Blader who is a genius but still puts in a lot of effort, and wields the Beyblade named Spriggan.",
    link: "https://aniwave.to/watch/beyblade-burst-evolution.vx14/ep-40",
  },
  {
    name: "Sweet Reincarnation",
    pic: "https://m.media-amazon.com/images/M/MV5BYzVmOThmZDktOTI1Ni00YTdhLWEzYzItZTUxYzdiMDZjNzMyXkEyXkFqcGdeQXVyMTU5NDMzOTg2._V1_FMjpg_UX1000_.jpg",
    info: "Nine-year-old Pastry Mille Morteln is from reincarnation and encounters the magical world. He must learn how to fight, utilizing his confectionary knowledge about pastry and discovering magic along the way.",
    link: "https://aniwave.to/watch/okashi-na-tensei.vv9xl/ep-1",
  },
  {
    name: "The Dreaming Boy is a Realist",
    pic: "https://m.media-amazon.com/images/M/MV5BODQzNDMyMGYtNTNjOS00Y2UwLTg0MmUtY2Q2ODAzZTAwMWI3XkEyXkFqcGdeQXVyMTIzNDEwODY@._V1_.jpg",
    info: "Wataru Sajou, who is deeply in love with his beautiful classmate Aika Natsukawa, approaches her without getting discouraged while having dreams about their mutual love. However, one day, he woke up thinking that he is not really fit to be together with someone as good as her.",
    link: "https://aniwave.to/watch/yumemiru-danshi-wa-genjitsushugisha.9ojy8/ep-9",
  },
  {
    name: "Malevolent Spirits: Mononogatari Cour 2",
    pic: "https://preview.redd.it/malevolent-spirits-mononogatari-season-2-key-visual-v0-8ktrnejkul0b1.jpg?width=640&crop=smart&auto=webp&s=6355445e433a2a679f6f8a07af72cf617c5b33b9",
    info: "When spirits cross over into the human world, they can possess old objects and gain a physical form: a tsukumogami. Tsukumogami can be gentle, violent, or somewhere in-between, so the Saenome clan peacefully helps send them back to the spirit world to avoid destruction.",
    link: "https://aniwave.to/watch/mononogatari-2nd-season.jvwp4/ep-9",
  },
  {
    name: "Synduality Noir",
    pic: "https://m.media-amazon.com/images/M/MV5BMzkwYWVjZTUtMWYyNy00OGVmLWI2N2QtZjhhZTg4MzhkNzI0XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg",
    info: "The year is 2242. Kanata wants to be a Drifter and meets Noir, who is a dud Magus with no memories. However, because Noir excels in battle against the Enders, Kanata partners with her and discovers exactly what it takes to be a Drifter.",
    link: "https://aniwave.to/watch/synduality.6lw54/ep-8",
  },
  {
    name: "Masamune-kun's Revenge R",
    pic: "https://m.media-amazon.com/images/M/MV5BYmEyZWNlMjAtYzNiYi00NjAwLTg5ZmItOWFhNjBlYmU2YjY2XkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    info: "As a child, Masamune Makabe once suffered greatly at the hands of a wealthy and beautiful girl named Aki Adagaki, who nicknamed him Piggy due to his chubby appearance. Seeking revenge against his tormentor, Masamune works hard to improve himself and returns as an incredibly handsome, albeit narcissistic, high school student.",
    link: "https://aniwave.to/watch/masamune-kun-no-revenge-r.7jwpy/ep-9",
  },
];
